- hosts: webservers
  gather_facts: no
  become: yes
  connection: local
  collections:
    - community.docker
    - kubernetes.core
  vars:
    customnamespace: default
  tasks:
    - name: start a container
      community.docker.docker_container:
        name: abc-dockercontainer
        image: avirup21/abcnewimage:13
        state: started
        ports:
          - 2255:8080

    - name: Create a Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-k8s-deployment
            namespace: "default"
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: abc-webapp
            template:
              metadata:
                labels:
                  app: abc-webapp
              spec:
                containers:
                - name: my-container
                  image: avirup21/abcnewimage:13

    - name: Create a Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abc-nodeportservice
            namespace: "default"
          spec:
            type: NodePort
            selector:
              app: abc-webapp
            ports:
            - name: http
              port: 80
              targetPort: 8080
        namespace: "default"
